[package]
name = "grom"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.8", features = ["derive"]}
cliclack = "0.3.2"
console = "0.15.8"
ctrlc = "3.4.4"
serde = { version = "1.0.204", features = ["derive"]}
toml = "0.8.14"
